### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Deech08** [ExcaliburZero/blender-astro-visualization#3]
When attempting to install I get this Error:

> error in blendplot setup command: "values of 'package_data' dict" must be a list of strings (got '[LICENSE]')

Able to fix it with this quick change to setup.py:

Change Line 21 from 

> '': 'LICENSE'

to 

> '': ['LICENSE']

Not sure if this is the best fix, or something else can solve the problem. 

P.S. - this is a really fun, easy to use tool!

**Comment by ExcaliburZero** [comment]
Ah, yep it looks like that might be due to https://github.com/pypa/setuptools/commit/8f848bd777278fc8dcb42dc45751cd8b95ec2a02

I'll make the change you mentioned (and update the Travis CI Python versions while I'm at it, 3.5 is pretty old now).

Thanks for letting me know!

I'm glad you enjoyed this tool! I wrote it back in college for a project where I was trying to create a video of a fly-through of a 3D plot for a planetarium video. I'm glad someone else found it useful.

**Comment by ExcaliburZero** [comment]
Here is a Travis CI build that reproduced the issue: https://travis-ci.org/github/ExcaliburZero/blender-astro-visualization/jobs/702929457

**Comment by ExcaliburZero** [comment]
Okay, this should be fixed now. The Travis CI build were able to reproduce it, and after the changes in #4 it looks to be fixed in the Travis CI builds.

Feel free to re-open the issue if it still occurs for you.
